version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: rpg-helper-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rpg-helper-db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rpg-helper-api:
    build: .
    container_name: rpg-helper-api
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/rpg-helper-db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - SERVER_PORT=8080
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=dev
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres_data: